name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x 
    - run: npm install
    - run: npm build
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Saca todos los archivos otra vez
      uses: actions/checkout@v1
    - name: rsync deployments
      uses: contention/rsync-deployments@v1.0.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        args: "-azvr --delete root@partnersinterno.com:/home/partners/dd/"
