name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: rsync deployments
      uses: contention/rsync-deployments@v1.0.0
      env:
        DEPLOY_KEY: "MIIEowIBAAKCAQEA0m7ug1xn0QTNwLbj2JZTqmq8nMYEbKznuR+aX8j0dJg3Td3Qow8suyE/VZYmIbGY9Oq64m4rNNaMO7bE3u7rguw2lwwj/JdMyxnz0C4lL+HkaffLRBqJE/RloV4JyNZOr2O1gYY3RqNQru1Dz4rpYw5SEx2BH5PfVilcm5hDX3KF9ZQT+G8yTM59ZU/jPIWNPP6mkRBmSi5F4km773oCOng8ADTiwz4BSxRGrqkiQ3J78Gp/qIkSDgMM5HIW18FOKEaDpJAJxIRCSTXKy2n0BCU+FubANnXRylv0Hz9YhDVuSumeLXSe12fc0JJGUnEgxGv2CAc7DvTAPxdIAiKfNwIBIwKCAQEAwGVsWtgkZ1TZX70oFnrQJsf85xtxwnIy8mYJfCVxya+9iQVRChyAqxcVVZCX5EqaeYYnNWwKPvALL0gEdA2kH+3oxJ1iuw39EXbQSU7C6fMZ+nwnjrks3wtVmtmii7yftkyIsO+9gmluVspMoH8BRJ9g+4iwkeZIiUpjTG30dIRNkcLkE4TKOlrgawhCl4sEA2mfP79cJCAXWV6NhgyRXDYOxTuBurQ6QoV2WByNv3EdRUF+ZlNKiVJQLmx/xlFqQShjTGpInfwDxX3gf083DtJuRla2cBE77M4VEz8H9VmPtYMiDD1NwOYToTMtWtEeqemuPGDf5CLCzhjKeRUWiwKBgQD3JLFpB2x+vmJYtgevjk8G9ueuL5uTUiMBSxf6gpfpFwG3dw4xwxcBPfr2V00o/+J4b7fZsIXi2q3fwV+C3oUI0UqQ8ns1Lg3cjnBEpD9uk1j8WNaNX9ad7wcDOVN479gFobSi+lqqYRfJkycUNe0ENAB3jgQoe8KRamB++j4iywKBgQDZ+XWBe6l2Xpi/Ojcq2HZ54ltyM7uGMIgrDXJWokRaJptkYW2bG/HgVFdW5vy+OixLfPMDuBgVrSMlcEvoOFM5H7fGFoCVKarBmsPYm+vhOJYZISFbTAxaUFOJ2N7u4ANzeq2N9bbna1RtxRs4gS9jBpPn5/kdsawpw0urk3VrxQKBgQDwFQQc4qPo1jOmojNaFTbTkMPNx9j1gv1u+H2xhi0rkrE14V4++Ae4EFLgrJQZMxaDn7npaaah277ZXMMurEa4G8THUfQHxlabvZGhxCBcyabmgi+CBVQkZIp4KQ9CSBOtswc/PFgTOb9WGetyuArQ4g8VDZ2jq2yNQsQjlAHYpwKBgQDHSnoP/AimvONtAgaNkrV2wFObnQM42+o1/apd1i/dZSBbxsqccVIsL9rTHFTLLd9a9eV/vkHn7sEMSWn44wpC2yuty24/PAnVlNBRA5XVOwzjxoTlwd9og/SbSfBlXxkZH7SfDIn4J52mMI3qhL2cXckOivJkSqwI7RH79IidCwKBgHcw0Nu5NX6zo2M22ApLa8a6Rna8wKXxSdn3eYOOXx461O8+Cdsdxbsyo/UqABYs8aC+lSH6kDIEAVPtKKoLNjfbqJN+iE/8EKwEI8/kG6m8KK0QcG0ZfnN5vzreLeoOJZZ0GMxIlrLrURzXq7i1CjuuaNL1uk9Rob9PNZERr5iK"
      with:
        args: "-azvr --delete root@198.57.226.5:/home/partners/dd/"
